export const componentsList = [
  {
    id: 0,
    name: "Action Icon",
    link: "/actionicon",
    topic: "inputs",
    description: "Icon button to indicate secondary action",
  },
  {
    id: 1,
    name: "Autocomplete",
    link: "/autocomplete",
    topic: "inputs",
    description: "Autocomplete user input with any list of options",
  },
  {
    id: 2,
    name: "Select",
    link: "/select",
    topic: "inputs",
    description: "Get user input from list of options",
  },
  {
    id: 3,
    name: "Button",
    link: "/button",
    topic: "inputs",
    description: "Just a button",
  },
  {
    id: 4,
    name: "Checkbox",
    link: "/checkbox",
    topic: "inputs",
    description: "Get true or false user input",
  },
  {
    id: 5,
    name: "Switch",
    link: "/switch",
    topic: "inputs",
    description: "Get true or false user input",
  },
  {
    id: 6,
    name: "Password Input",
    link: "/passwordinput",
    topic: "inputs",
    description: "Get true or false user input",
  },
  {
    id: 7,
    name: "Text Input",
    link: "/textinput",
    topic: "inputs",
    description: "Simply get user input",
  },
  {
    id: 8,
    name: "Text Area",
    link: "/textarea",
    topic: "inputs",
    description: "Get user input with resizeable input container",
  },
  {
    id: 9,
    name: "Accordion",
    link: "/accordion",
    topic: "dataDisplay",
    description: "Divide content into collapsible sections",
  },
  {
    id: 10,
    name: "Card",
    link: "/card",
    topic: "dataDisplay",
    description: "Card with context styles for Image and Divider components",
  },
  {
    id: 11,
    name: "Kbd",
    link: "/kbd",
    topic: "dataDisplay",
    description: "Display keyboard button or keys combination",
  },
  {
    id: 12,
    name: "Notifications",
    link: "/notifications",
    topic: "dataDisplay",
    description: "Show dynamic notifications and alerts to user",
  },
  {
    id: 13,
    name: "Affix",
    link: "/affix",
    topic: "overlay",
    description: "Scroll to top button",
  },
  {
    id: 14,
    name: "Modal",
    link: "/modal",
    topic: "overlay",
    description: "Display content in overlaying window",
  },
  {
    id: 15,
    name: "Skeleton",
    link: "/skeleton",
    topic: "utils",
  },
  {
    id: 16,
    name: "Divider",
    link: "/divider",
    topic: "utils",
    description: "",
  },
];
