export const componentsList = [
  {
    id: 0,
    name: "Action Icon",
    link: "/actionicon",
    topic: "inputs",
  },
  {
    id: 1,
    name: "Autocomplete",
    link: "/autocomplete",
    topic: "inputs",
  },
  {
    id: 2,
    name: "Select",
    link: "/select",
    topic: "inputs",
  },
  {
    id: 3,
    name: "Button",
    link: "/button",
    topic: "inputs",
  },
  {
    id: 4,
    name: "Checkbox",
    link: "/checkbox",
    topic: "inputs",
  },
  {
    id: 5,
    name: "Switch",
    link: "/switch",
    topic: "inputs",
  },
  {
    id: 6,
    name: "Password Input",
    link: "/passwordinput",
    topic: "inputs",
  },
  {
    id: 7,
    name: "Text Input",
    link: "/textinput",
    topic: "inputs",
  },
  {
    id: 8,
    name: "Text Area",
    link: "/textarea",
    topic: "inputs",
  },
  {
    id: 9,
    name: "Accordion",
    link: "/accordion",
    topic: "dataDisplay",
  },
  {
    id: 10,
    name: "Card",
    link: "/card",
    topic: "dataDisplay",
  },
  {
    id: 11,
    name: "Kbd",
    link: "/kbd",
    topic: "dataDisplay",
  },
  {
    id: 12,
    name: "Notifications",
    link: "/notifications",
    topic: "dataDisplay",
  },
  {
    id: 13,
    name: "Affix",
    link: "/affix",
    topic: "overlay",
  },
  {
    id: 14,
    name: "Modal",
    link: "/modal",
    topic: "overlay",
  },
  {
    id: 15,
    name: "Skeleton",
    link: "/skeleton",
    topic: "utils",
  },
  {
    id: 16,
    name: "Divider",
    link: "/divider",
    topic: "utils",
  },
];
